[package]
name = "wa-kalshi"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
wa-book = { path = "../wa-book" }
reqwest.workspace = true
rsa.workspace = true
sha2.workspace = true
rand.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
